### ISSUE TITLE
fix link to horizon-computing.com

### ISSUE THREAD

**Issue by orangecms** [linuxboot/linuxboot.org#42]
The website has been down for a while since the acquisition ( https://www.itrenew.com/press-releases/itrenew-acquires-splitted-desktop-systems-sds/ ). Should we link to ITRenew instead? And add HPE, on that note?

**Comment by vejmarie** [comment]
yes linking to itrenew is fair. I'll be glad if we could add hpe, as we are moving forward and a couple of hpe people are currently contributing !
